# Generated by Django 4.1.7 on 2023-02-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trainmodel_clock_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainmodel',
            name='bluetooth',
            field=models.BinaryField(verbose_name='bluetooth'),
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='dual_sim',
            field=models.BinaryField(verbose_name='dual_sim'),
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='four_g',
            field=models.BinaryField(verbose_name='4G'),
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='three_g',
            field=models.BinaryField(verbose_name='3G'),
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='touch_screen',
            field=models.BinaryField(verbose_name='touch screen'),
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='wifi',
            field=models.BinaryField(verbose_name='wifi'),
        ),
    ]
