# Generated by Django 4.1.7 on 2023-02-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_power', models.IntegerField(verbose_name='battery power')),
                ('bluetooth', models.BooleanField(verbose_name='bluetooth')),
                ('clock_speed', models.DecimalField(decimal_places=1, max_digits=1, verbose_name='clock_speed')),
                ('dual_sim', models.BooleanField(verbose_name='dual_sim')),
                ('front_camera', models.IntegerField(verbose_name='front_camera')),
                ('four_g', models.BooleanField(verbose_name='4G')),
                ('internal_memory', models.IntegerField(verbose_name='internal_memory')),
                ('mobile_depth', models.DecimalField(decimal_places=1, max_digits=1, verbose_name='mobile_depth')),
                ('mobile_weight', models.IntegerField(verbose_name='mobile_weight')),
                ('number_cores', models.IntegerField(verbose_name='number_cores')),
                ('primary_camera', models.IntegerField(verbose_name='primary_camera')),
                ('px_height', models.IntegerField(verbose_name='px_height')),
                ('px_width', models.IntegerField(verbose_name='px_width')),
                ('ram', models.IntegerField(verbose_name='RAM')),
                ('screen_height', models.IntegerField(verbose_name='screen_height')),
                ('screen_width', models.IntegerField(verbose_name='screen_width')),
                ('talk_time', models.IntegerField(verbose_name='talk_time')),
                ('three_g', models.BooleanField(verbose_name='3G')),
                ('touch_screen', models.BooleanField(verbose_name='touch screen')),
                ('wifi', models.BooleanField(verbose_name='wifi')),
                ('price_range', models.IntegerField(verbose_name='price range')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
